---
driver:
  name: vagrant
  customize:
    memory: 1024
  require_chef_omnibus: true
  network:
    - ["forwarded_port", {guest: 80, host: 8888}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ubuntu::default]
      - recipe[drone::default]

  - name: extended  # https, docker, config
    run_list:
      - recipe[ubuntu::default]
      - recipe[drone::default]
    attributes:
      drone:
        install_method: package
        docker_tls: true
        generate_certs: true
        install_docker: true
        server_address: ':443'
        server_crt: /etc/ssl/certs/self-signed-server.pem
        server_key: /etc/ssl/private/self-signed-server.key
