---
driver:
  name: vagrant
  customize:
    memory: 1024
  require_chef_omnibus: true

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-15.04
  - name: ubuntu-15.10
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[ubuntu::default]
      - recipe[drone::default]
      - recipe[drone::reverse_proxy]
