---
driver_plugin: vagrant

driver_config:
  customize:
    memory: 1024
  require_chef_omnibus: latest

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:

  - name: default
    run_list:
      - recipe[drone::default]
    attributes:
      drone:
        server_address: ':80'

  - name: extended  # https, docker, config
    run_list:
      - recipe[drone::default]
    attributes:
      drone:
        docker_tls: true
        generate_certs: true
        install_docker: true
        server_address: ':443'
        server_crt: /etc/ssl/certs/self-signed-server.pem
        server_key: /etc/ssl/private/self-signed-server.key
