---
driver:
  name: vagrant
  customize:
    memory: 1024
  require_chef_omnibus: true

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-15.10
    run_list:
      - recipe[ubuntu::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[ubuntu::default]
  - name: centos-7.2
    run_list:
      - recipe[yum-epel::default]

suites:
  - name: default
    run_list:
      - recipe[drone::default]
      - recipe[drone::reverse_proxy]
    attributes:
      drone:
        docker:
          daemon:
            log_level: debug

  - name: drone05
    run_list:
      - recipe[drone::default]
      - recipe[drone::agent]
      - recipe[drone::reverse_proxy]
    attributes:
      drone:
        agent:
          config:
            I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: true
            I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: true
            drone_server: http://10.0.2.15:8000
        config:
          I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: true
          I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: true
          DRONE_GITHUB: true
          DRONE_GITHUB_CLIENT: GH_CLIENT
          DRONE_GITHUB_SECRET: GH_SECRET
        docker:
          daemon:
            log_level: debug
        version: '0.5'
